# Generated by Django 5.1.2 on 2024-10-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='usuario',
            new_name='aluno',
        ),
    ]
