# Generated by Django 5.1.2 on 2024-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_rename_usuario_emprestimo_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_exemplares',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
